### ISSUE TITLE
Add endpoint returning names starting with or contains passed string

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-middleware#114]
This will allow building autosuggest interfaces like:
![image](https://user-images.githubusercontent.com/9007851/62094705-4f71eb00-b27e-11e9-9daa-e4cddaf23aa7.png)

**Comment by shekhar-shubhendu** [comment]
already there `GET /middleware/names/<name>`

**Comment by davidyuk** [comment]
@shekhar-shubhendu how I can get all names starting with `example` by that endpoint?

**Comment by shekhar-shubhendu** [comment]
try this: `https://alpha.mdw.aepps.com/middleware/names/exam`

**Comment by davidyuk** [comment]
When it will get deployed to testnet.mdw.aepps.com/mdw.aepps.com?

**Comment by davidyuk** [comment]
Looks like this API is released on both testnet and mainnet.
