### ISSUE TITLE
Duplicate names on testnet.mdw.aepps.com

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-middleware#117]
Issue #92 is not fixed yet. In https://testnet.mdw.aepps.com/middleware/names/reverse/ak_2D8eLLbqfJGiaB1Mj2VuqYAMscWHCMNj7JbbxvUPwM8mZ9nLnM `asdfasdfxcv.test` name is mentioned 24 times. We have noticed this after releasing of the Base app, so our "Names" tab shows duplicate names aswell.

**Comment by davidyuk** [comment]
Is it fixed? I have not seen this bug for a while.

**Comment by shekhar-shubhendu** [comment]
@davidyuk from our side this seems to be fixed. please check on your side too and close the issue if it is.
