### ISSUE TITLE
Spend transactions to sub-account not shown in the mdw and explorer.

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-middleware#131]
Spend transactions sent from pubkey0 to pubkey1 and so on are not present in the middleware's history nor in the explorers relying on the middleware.

**Comment by shekhar-shubhendu** [comment]
@mradkov can you please expand more on this?
if possible provide a sample transaction that is affected by this.

**Comment by johnsnewby** [comment]
hi there,

could you give an example of what you were expecting to see? I don't really understand from this what this issue is about?

**Comment by mradkov** [comment]
Steps to reproduce: create a keypair, derive second public key and send a spendtx from the main account to the sub-account.

Main account [at index 0 according to the derivation path]
https://testnet.explorer.aepps.com/#/account/ak_2DDLbYBhHcuAzNg5Un853NRbUr8JVjZeMc6mTUpwmiVzA4ic6X

Sends transaction to

Sub-Account  [at index 1 according to the derivation path]
https://testnet.explorer.aepps.com/#/account/ak_SBB3rVpunffTTh1EiLtKo8WUaPPRYyuSCxB3i8SseAZB7fzje

===
Result:

Tx is not visible for neither of those.

It is persisted on-chain and can be found here:

https://testnet.explorer.aepps.com/#/tx/th_dAEWH1hZ637xpkpmYcFxbw2pEpxT1od5tGpUr1422xh8B9557

**Comment by johnsnewby** [comment]
OK I don't understand why but this one was not in the DB--when I made it load the tx again, it went in. Do you have other missing transactions?

**Comment by mradkov** [comment]
All faucet transactions are missing as well:

https://testnet.explorer.aepps.com/#/account/ak_2UinZiRYBEGAVZqbciZUNCVSNvSHddUCdUACwk4ZqDprzTsKKP

https://testnet.explorer.aepps.com/#/tx/th_5j7XKfNsqSfhZAEz59k7B45Uk4z4GT2NpTgSSWfxbZt8tXLj9

**Comment by johnsnewby** [comment]
Loads are missing! Looks like a wider problem. I am manually reloading all blocks into the testnet mdw right now which should correct the issue until I can make a better fix.

**Comment by mradkov** [comment]
Not sure how long ago this originates, but I assume there might also be other stuff missing/affected.

It will be good if there is a way to verify everything after reloading this into the mdw.

**Comment by davidyuk** [comment]
I have sent 2 ae in two transactions from ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ to ak_212Jw6LJGMCKB5yRo8E3esazSDdC1ZyDcbzenh8PfkAXHJKvFV. But `transactions/account` doesn't display them: https://testnet.mdw.aepps.com/middleware/transactions/account/ak_212Jw6LJGMCKB5yRo8E3esazSDdC1ZyDcbzenh8PfkAXHJKvFV. It looks like a related issue, but these two accounts are generated by different mnemonics.

**Comment by j28** [comment]
do you know when this will be addressed/resolved?

**Comment by shekhar-shubhendu** [comment]
this should be resolved on with the release of 0.9.2. Please check and let us know. @mradkov @davidyuk

**Comment by mradkov** [comment]
Okay, will check it now.

**Comment by mradkov** [comment]
I can confirm the issue is resolved now.

> this should be resolved with the release of 0.9.2. Please check and let us know. @mradkov @davidyuk
