### ISSUE TITLE
🚀 Include additional fields in generation response object 

### ISSUE THREAD

**Issue by shekhar-shubhendu** [aeternity/aepp-middleware#14]
Add below fields in the generation object:
- Block/Generation Reward
- Total Transactions
- Total AE transacted

**Comment by jsnewby** [comment]
Reward is not returned by the chain (?) but calculated, which I can do, but it's a new feature.
Total tx seems easy
Total AE transacted == all spend TXs added together? Remember that contracts won't be counted.
