### ISSUE TITLE
`names/auctions/active`: Add filter by character length

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-middleware#184]
To implement this screen: https://app.zeplin.io/project/5ce5002ad64fdd1e1600ee8f/screen/5d6ec64a2dba3f9bc1728102

**Comment by shekhar-shubhendu** [comment]
check the comment on #186

**Comment by davidyuk** [comment]
@shekhar-shubhendu I propose to add an additional `lendth` parameter accepting an integer value, the length of all names in the output should be equal to the parameter value. Is it clear?

**Comment by johnsnewby** [comment]
http://aeternal.io:8000/middleware/names/auctions/active?length=6

as ever please reopen if necessary
