### ISSUE TITLE
`names/auctions/active`: Add current address and bid

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-middleware#185]
An address of the account that made the biggest bid

To make this screen: https://app.zeplin.io/project/5ce5002ad64fdd1e1600ee8f/screen/5d6ec64ae707141ab7878b9c

**Comment by shekhar-shubhendu** [comment]
check comment on #186

**Comment by davidyuk** [comment]
@shekhar-shubhendu I propose to add two fields in every object in the output:
 - `address` should contain the account address that has made the biggest/latest bid
- `latest-bid`(?) should contain the number of tokens of the biggest/latest bid

**Comment by johnsnewby** [comment]
Done, please check http://aeternal.io:8000/middleware/names/auctions/active?page=2&limit=2 and reopen if necessary
