### ISSUE TITLE
Add possibility to get an address and a name of an account by the hash of the name

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-middleware#193]
to be able to show right identicon while signing or browsing the transactions (based on a hash of the name) in the base Aepp

**Comment by shekhar-shubhendu** [comment]
@CedrikNikita my suggestions:
- endpoint: `/middleware/names/hash/<name_hash>`

- response example: 
```
{
    "name": "dead.test",
    "name_hash": "nm_k9C26LsmrrB8s6URnDAFmKbQfkQzA4A5aEFif2cFoDYYeXaJp",
    "tx_hash": "th_Fb8NRUiD8AXk37LGoiHG4v2M7sbMNViLpS5pw1JHrgN7AzDLU",
    "created_at_height": 16754,
    "owner": "ak_2WZoa13VKHCamt2zL9Wid8ovmyvTEUzqBjDNGDNwuqwUQJZG4t",
    "expires_at": 92723,
    "pointers": [
      {
        "id": "ak_2WZoa13VKHCamt2zL9Wid8ovmyvTEUzqBjDNGDNwuqwUQJZG4t",
        "key": "account_pubkey"
      }
    ]
  }
```

**Comment by johnsnewby** [comment]
http://aeternal.io:8000/middleware/names/hash/nm_vw9SJqGSCt2HzTqXn6xdq2j67kj52kNWUrML2nVbkWJMWKAKK

Please check, re-open this if necessary. Please note that the underlying name logic needs updating for the auction logic, so the results may be off for a short while.
