### ISSUE TITLE
Implement endpoint that return number of records that `names/auctions/active` returns with the same arguments

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-middleware#195]
It is needed to determine the number of the last page

**Comment by johnsnewby** [comment]
http://aeternal.io:8000/middleware/names/auctions/active/count?length=6

as ever, reopen this issue if necessary.

**Comment by davidyuk** [comment]
It works, thank you!

If it would be needed in the future: I don't see `reopen` button, can you enable it somehow?

![Screenshot 2019-10-11 at 12 49 11](https://user-images.githubusercontent.com/9007851/66646113-8755c100-ec25-11e9-9f43-48636dc75782.png)
