### ISSUE TITLE
`/middleware/names/auctions/active` not listing names with > 10 chars

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-middleware#207]
currently I am testing our java sdk functionalities and query the middleware using the official docker-image (`latest`) which @noandrea built for me.

I experienced the issue that names with >10 chars are not appearing in the list of active auctions.

I expect all names to appear in this list when the character-length is <=12

**Comment by marc0olo** [comment]
and names which have an active auction running also immediately appear when calling `/middleware/names`.
- is this the expected behaviour? I would expect them to appear there when the auction has ended

**Comment by marc0olo** [comment]
mhhh probably this isn't only affecting names > 10 characters. now I also got the problem with `auction99.chain` which has 9 chars.

**Comment by johnsnewby** [comment]
This was a bug in the auction length code which is now fixed.
