### ISSUE TITLE
Implement missing oracles endpoints

### ISSUE THREAD

**Issue by maptuhec** [aeternity/aepp-middleware#24]
In this swagger, some of oracles functionalities are listed as endpoints which can be easily tested with and rest api.  Some which are important are missing though.

Missing endpoints in my opinion are:
 - get answer
 - get question 

Thanks

**Comment by johnsnewby** [comment]
Hey, yes this is a good request. It's non-trivial, which is why we haven't done it, but we need to. I'll have a think about how best to do this.

**Comment by johnsnewby** [comment]
Hey @maptuhec we have Qs and As for a given oracle now, but I have a feeling this isn't what you were asking for here-- http://mdw.aepps.com:8000/middleware/oracles/ok_28QDg7fkF5qiKueSdUvUBtCYPJdmMEoS73CztzXCRAwMGKHKZh

let me know what else would be good

**Comment by maptuhec** [comment]
hey, Mr @johnsnewby as far as I remember the middleware implemented all of the endpoints that the node provided, but with the great benefit that you are more flexible than the node and you can implement feature request like mine more easily.

So in this swagger : http://aeternity.com/api-docs/ there are several endpoints for oracles like register, query, extend etc.

In my opinion, it would be great if we can query also the answers and questions of an oracle which for example is done when providing the **oracle_id** and the **query_id**.

If you have already implemented this, you are already awesome and I thank you.

Is this documentation up-to-date https://github.com/aeternity/aepp-middleware#supported-queries?

Thanks!,
Martin

**Comment by johnsnewby** [comment]
Hey Martin, so you get all of the Qs and As for an oracle, but you can't query a specific query. I don't think that's necessary, certainly now, but it can be implemented if necessary.

The documentation is up-to-date as far as I know :)

Closing this, please re-open if you want.

**Comment by olegshmuelov** [comment]
Hey @johnsnewby, it would be great if we can query a specific query of the specific oracle.

Thanks,
Oleg
