### ISSUE TITLE
Add CORS header to solve problems with ionic

### ISSUE THREAD

**Issue by etharner** [aeternity/aepp-middleware#32]
![image](https://user-images.githubusercontent.com/7098449/55722403-90cd5900-5a49-11e9-936a-f131e2a6be12.png)
I'm experiencing issues with CORS in ionic webview engine for Base Aepp Cordova native ios builds. It seems like it can be solved by adding ```ionic://localhost``` to CORS header for responses from middleware like sdk epoch node did:
```
Response
:status: 200
Access-Control-Allow-Credentials: true
Content-Type: application/json
Access-Control-Allow-Methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT
Access-Control-Max-Age: 1800
Vary: Accept-Encoding
Date: Mon, 08 Apr 2019 11:17:45 GMT
Content-Length: 107
Access-Control-Allow-Origin: ionic://localhost
Server: Cowboy
```
for example for https://sdk-testnet.aepps.com/v2/accounts/ak_DzELMKnSfJcfnCUZ2SbXUSxRmFYtGrWmMuKiCx68YKLH26kwc
As we see, it set it's own Access-Control-Allow-Origin in response to Origin in request

**Comment by davidyuk** [comment]
```
$ curl -H "Origin: ionic://localhost" -I https://testnet.mdw.aepps.com/middleware/transactions/account/ak_DzELMKnSfJcfnCUZ2SbXUSxRmFYtGrWmMuKiCx68YKLH26kwc
HTTP/2 200 
access-control-allow-credentials: true
access-control-allow-origin: null
content-type: application/json
date: Thu, 18 Apr 2019 02:10:18 GMT
server: Caddy
server: Rocket
vary: Origin
content-length: 82239
```
Why middleware replies with `access-control-allow-origin: null` instead of `access-control-allow-origin: ionic://localhost`?

**Comment by davidyuk** [comment]
Now we have switched to `cordova-plugin-wkwebview-engine` and our origin is `null` because of `file://` protocol that used to open app in WebView. The middleware is not allowing to fetch a response in this case as well.

**Comment by davidyuk** [comment]
Middleware deployed on testnet.mdw.aepps.com works. Thank you @jsnewby!
```
$ curl -H "Origin: null" -I https://testnet.mdw.aepps.com/middleware/transactions/account/ak_DzELMKnSfJcfnCUZ2SbXUSxRmFYtGrWmMuKiCx68YKLH26kwc
HTTP/2 200 
access-control-allow-credentials: true
access-control-allow-origin: null
content-type: application/json
date: Thu, 25 Apr 2019 09:24:39 GMT
server: Caddy
server: Rocket
vary: Origin
content-length: 113512

$ curl -H "Origin: ionic://localhost" -I https://testnet.mdw.aepps.com/middleware/transactions/account/ak_DzELMKnSfJcfnCUZ2SbXUSxRmFYtGrWmMuKiCx68YKLH26kwc
HTTP/2 200 
access-control-allow-credentials: true
access-control-allow-origin: ionic://localhost
content-type: application/json
date: Thu, 25 Apr 2019 09:32:25 GMT
server: Caddy
server: Rocket
vary: Origin
content-length: 113512
```

**Comment by johnsnewby** [comment]
Done, please check, and re-open this issue if there are still problems
