### ISSUE TITLE
How the output of `transactions/account/<account>` is ordered?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-middleware#52]
For me would be reasonable to get them ordered by `time` as far as we are doing the same in Base app. In another case, the next page from middleware can modify the content of already displayed pages that adds some flickering to UI. And also it makes the user check already seen pages because the transaction that he is looking for can apper there.

I have this problem with middleware response on https://testnet.mdw.aepps.com/middleware/transactions/account/ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ?limit=15&page=2:
```js
[
    // ...
    {
        "block_height": 83894,
        "time": 1558499595860,
        // ...
    },
    {
        "block_height": 83659,
        "time": 1558456617361,
        // ...
    },
    {
        "block_height": 83659,
        "time": 1558456617361,
        // ...
    },
    {
        "block_height": 83444,
        "time": 1558416558527,
        // ...
    },
    {
        "block_height": 83446,
        "time": 1558417303333,
        // "block_height" and "time" are bigger than in the previous transaction
        // ...
    },
    {
        "block_height": 83447,
        "time": 1558417398042,
        // ...
    },
    {
        "block_height": 83448,
        "time": 1558417779644,
        // ...
    },
    {
        "block_height": 83448,
        "time": 1558417776644,
        // ...
    }
]
```

**Comment by johnsnewby** [comment]
they're ordered by id, which ought to be a proxy for time, but forks can change this. I can trivially change this to time. Just let me know.

**Comment by davidyuk** [comment]
Would be great if you do it. We have troubles testing our stuff without proper ordering.

**Comment by johnsnewby** [comment]
I have done this, and released it onto the middleware which is running here:

mainnet: http://mdw.aepps.com:8000/middleware/transactions/account/ak_nv5B93FPzRHrGNmMdTDfGdd5xGZvep3MVSpJqzcQmMp59bBCv

testnet: http://mdw.aepps.com:8005/middleware/transactions/account/ak_nv5B93FPzRHrGNmMdTDfGdd5xGZvep3MVSpJqzcQmMp59bBCv

I am currently looking at how to speed these queries up

**Comment by johnsnewby** [comment]
I added indices, 80% faster now on the SQL query

**Comment by davidyuk** [comment]
it works, thank you! can we push Base app that depends on http://mdw.aepps.com:8000 to production?
