### ISSUE TITLE
Power-user useful features for the frontend

### ISSUE THREAD

**Issue by randomshinichi** [aeternity/aepp-middleware#72]
I was writing some tests for the swagger client, and wanted to test against things in testnet.

These were the most obviously needed things:

need to find/filter txs by TransactionType/age/height
can I sort keyblocks by number of microblocks contained within? please
what names/oracles/contracts are NOT EXPIRED? Would be great if this was an endpoint, so I can query it and pick a random one in my unittests
is it just me or https://testnet.mdw.aepps.com/transactions Load more button doesn't work after a certain point?

**Comment by shekhar-shubhendu** [comment]
@randomshinichi 

Will try to do this.
> need to find/filter txs by TransactionType/age/height

maybe yes. number of microblocks and transactions.
> can I sort keyblocks by number of microblocks contained within? please

Not a front-end feature. can you create a separate issue with request and response format?
> what names/oracles/contracts are NOT EXPIRED? Would be great if this was an endpoint, so I can query it and pick a random one in my unittests

works for me. There is edge case I'm aware of where the store gets filled through the WebSocket subscription but the page pointer for load more button still stays at the same place. Will check if I can resolve this.
> is it just me or https://testnet.mdw.aepps.com/transactions Load more button doesn't work after a certain point?
