### ISSUE TITLE
Prevent caching of pages in front-end

### ISSUE THREAD

**Issue by johnsnewby** [aeternity/aepp-middleware#73]
b/c currently one gets old blocks when clicking the 'generations' page. Which is bad.

**Comment by shekhar-shubhendu** [comment]
@johnsnewby  instead, we can check for if their are new blocks and then load them too before rendering.

**Comment by johnsnewby** [comment]
YES THAT

**Comment by shekhar-shubhendu** [comment]
this is handled in a way by the WebSocket subscription too. I will check why the connection is breaking or maybe store is not updated. there are couple of bugs i'm aware of.
