### ISSUE TITLE
Can't build docker image

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-middleware#82]
```
$ cd docker
$ docker build ./
Sending build context to Docker daemon  13.82kB
Step 1/19 : FROM rust:1.35.0 as build
 ---> cc8fdbea4a2a
Step 2/19 : RUN rustup default nightly
 ---> Using cache
 ---> 99a2aeba42e1
Step 3/19 : RUN USER=root cargo new --bin aepp-middleware
 ---> Running in 7b9b5d491591
error: Failed to create package `aepp-middleware` at `/aepp-middleware`

Caused by:
  failed to make directory '/aepp-middleware/.git': No such file or directory; class=Os (2)
The command '/bin/sh -c USER=root cargo new --bin aepp-middleware' returned a non-zero code: 101
```
Switching to stable helps in this case:
```diff
-RUN rustup default nightly
+RUN rustup default stable
```

**Comment by davidyuk** [comment]
Actually, for some reason, `pear_codegen` depends on a nightly version, and I was able to build middleware using `nightly-2019-05-20`, where 2019-05-20 is the date of the latest stable release.

**Comment by shekhar-shubhendu** [comment]
@davidyuk middleware uses the nightly version of rust and it is recommended.
the issue mentioned above has been solved in this commit https://github.com/aeternity/aepp-middleware/commit/b4cfee4aa76796875f6b9eaae4be4736ee4fc0f4

closing the issue.

**Comment by davidyuk** [comment]
Who recommends to depend on the nightly version? Can you give a link?

As I see, the nightly version can contain unexpected bugs as I have reported above. Would be better to depend on a stable one or at least to depend on the specific nightly version to avoid such problems in the future.
