### ISSUE TITLE
Deploy the latest changes to testnet.mdw.aepps.com

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-middleware#83]
As I see, the current develop branch has a fixed version of `/middleware/names/active` endpoint. Would be great to be able to use it in the stuff that we are building in the Base app.

Also, `/middleware/names/reverse` is not working for me: [it returns the empty array](https://testnet.mdw.aepps.com/middleware/names/reverse/ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ) for my address but I have registered several names using http:/aeternity.com/aepp-naming-example/. For instance, I have registered `example.test`: https://sdk-testnet.aepps.com/v2/names/example.test.

I can't check is it fixed in develop because middleware sync takes a while to get synced. Do you have a middleware from develop branch deployed somewhere?

**Comment by shekhar-shubhendu** [comment]
the updated version is deployed to the below URLs. All issues reported seem to be fixed.
https://mdw.aepps.com
https://testnet.mdw.aepps.com
https://alpha.mdw.aepps.com

@davidyuk please check and let us know if it works for you.

**Comment by davidyuk** [comment]
> All issues reported seem to be fixed.

Are you sure that you have you checked them?

I have registered [example.test](https://sdk-testnet.aepps.com/v2/names/example.test) on testnet and [middleware/names/reverse](https://testnet.mdw.aepps.com/middleware/names/reverse/ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ) still returns the empty array. [middleware/names/active](https://testnet.mdw.aepps.com/middleware/names/active) also returns the empty array.

**Comment by davidyuk** [comment]
Actually, it works for newly registered names, it is needed to sync names that were created before.
