### ISSUE TITLE
Cargo build: Could not compile `pear_codegen`

### ISSUE THREAD

**Issue by cypheron** [aeternity/aepp-middleware#9]
`error[E0432]: unresolved import `syntax::tokenstream::ThinTokenStream`
  --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.20/src/lib.rs:15:51
   |
15 | use syntax::tokenstream::{TokenTree, TokenStream, ThinTokenStream};
   |                                                   ^^^^^^^^^^^^^^^ no `ThinTokenStream` in `tokenstream`. Did you mean to use `TokenStream`?

error[E0599]: no function or associated item named `concat` found for type `syntax::tokenstream::TokenStream` in the current scope
   --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.20/src/lib.rs:330:67
    |
330 |                 mac.node.tts = ThinTokenStream::from(TokenStream::concat(streams));
    |                                                      -------------^^^^^^
    |                                                      |
    |                                                      function or associated item not found in `syntax::tokenstream::TokenStream`

error: aborting due to 2 previous errors

Some errors occurred: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `pear_codegen`.
warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by jsnewby** [comment]
Hi there,

Super sorry--we'd made master the default branch, it should have been develop. If you checkout develop branch, that works.

**Comment by cypheron** [comment]
@jsnewby you're right, develop branch compiles just fine. Do you want me to keep this issue open until master is fixed?

**Comment by jsnewby** [comment]
Yes, let's.

**Comment by johnsnewby** [comment]
Closing this now that master is sane again
