### ISSUE TITLE
Request: smart contract bytecode GET endpoint

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-middleware#98]
It will be quite handy to have an endpoint in the middleware that returns the smart contract's bytecode. e.g. `/middleware/contracts/<address>/bytecode`

This will could be used for verifying the smart contract functionality.

Example use-case:
Aepp Developer provides smart contract code in github 
-> user compiles it locally
-> verifies if the compiled bytecode matches the one on the provided address by developer
-> safely interact with smart contract.

P.S. Now when I'm writing this issue I think this could be further improved by having a `meta-info` endpoint - which could return the smart contract owner, the bytecode and other info that might end up in the meta. You can consider that as well.

**Comment by johnsnewby** [comment]
OK to close this, since the info is provided by /contracts/transactions/address/<address> ?

regarding your postscript, the owner, if not the creator and in the logic, is not knowable by the middleware, as things currently stand.

re-open if this is not OK!
